import { Archive, ChevronRight, CircleHelp, Globe2, Palette, RotateCcw, Trash2 } from 'lucide-react'
import { useState } from 'react'
import type { ReactNode } from 'react'
import { categoryText, languages, themeLabel, useTranslation } from '../i18n'
import { chanceCategories, mainCategories, upperCategories } from '../game/rules'
import { backgroundThemes, gridThemes } from '../theme/themes'
import type { AppearancePreferences } from '../theme/types'
import { BottomSheet } from './BottomSheet'

type SettingsView = 'home' | 'appearance' | 'language' | 'rules' | 'clearHistory'
interface SettingsSheetProps { appearance: AppearancePreferences; onClose: () => void; onAppearanceChange: (appearance: AppearancePreferences) => void; onResetAppearance: () => void; onOpenHistory: () => void; onClearHistory: () => void; initialView?: 'home' | 'appearance' }

export function SettingsSheet(props: SettingsSheetProps) {
  const [view, setView] = useState<SettingsView>(props.initialView ?? 'home')
  const { t } = useTranslation()
  const title = view === 'appearance' ? t('appearance') : view === 'language' ? t('language') : view === 'rules' ? t('rules') : view === 'clearHistory' ? t('clearHistoryTitle') : t('settings')
  return <BottomSheet title={title} onClose={props.onClose} onBack={view === 'home' ? undefined : () => setView('home')} className="settings-sheet">
    {view === 'home' && <SettingsHome language={props.appearance.language} onAppearance={() => setView('appearance')} onLanguage={() => setView('language')} onRules={() => setView('rules')} onHistory={props.onOpenHistory} onReset={props.onResetAppearance} onClearHistory={() => setView('clearHistory')} />}
    {view === 'appearance' && <AppearancePicker appearance={props.appearance} onChange={props.onAppearanceChange} />}
    {view === 'language' && <LanguagePicker language={props.appearance.language} onChange={(language) => props.onAppearanceChange({ ...props.appearance, language })} />}
    {view === 'rules' && <RulesView />}
    {view === 'clearHistory' && <ClearHistory onCancel={() => setView('home')} onConfirm={props.onClearHistory} />}
  </BottomSheet>
}

export function AppearancePicker({ appearance, onChange }: { appearance: AppearancePreferences; onChange: (appearance: AppearancePreferences) => void }) {
  const { language, t } = useTranslation()
  return <div className="appearance-picker"><p className="sheet-intro">{t('independentAppearance')}</p><ThemeOptions title={t('gridColor')} options={gridThemes} selected={appearance.gridTheme} onSelect={(gridTheme) => onChange({ ...appearance, gridTheme })} label={(id) => themeLabel(language, id)} /><ThemeOptions title={t('backgroundTheme')} options={backgroundThemes} selected={appearance.backgroundTheme} onSelect={(backgroundTheme) => onChange({ ...appearance, backgroundTheme })} label={(id) => themeLabel(language, id)} /></div>
}
function ThemeOptions<T extends string>({ title, options, selected, onSelect, label }: { title: string; options: readonly { id: T; preview: string }[]; selected: T; onSelect: (id: T) => void; label: (id: T) => string }) { return <section className="appearance-section"><h3>{title}</h3><div className="theme-options">{options.map((option) => <button type="button" className={`theme-option ${selected === option.id ? 'selected' : ''}`} key={option.id} onClick={() => onSelect(option.id)} aria-pressed={selected === option.id}><span className="theme-swatch" style={{ background: option.preview }} /><span>{label(option.id)}</span></button>)}</div></section> }
function LanguagePicker({ language, onChange }: { language: AppearancePreferences['language']; onChange: (language: AppearancePreferences['language']) => void }) { const { t } = useTranslation(); return <section className="appearance-section"><p className="sheet-intro">{t('language')}</p><div className="theme-options">{languages.map((option) => <button type="button" className={`theme-option ${language === option.id ? 'selected' : ''}`} key={option.id} onClick={() => onChange(option.id)} aria-pressed={language === option.id}><span>{option.label}</span></button>)}</div></section> }
function SettingsHome({ language, onAppearance, onLanguage, onRules, onHistory, onReset, onClearHistory }: { language: AppearancePreferences['language']; onAppearance: () => void; onLanguage: () => void; onRules: () => void; onHistory: () => void; onReset: () => void; onClearHistory: () => void }) { const { t } = useTranslation(); return <div className="settings-home"><SettingsSection title={t('appearance')}><SettingsRow icon={<Palette size={19} />} label={t('appearance')} detail={t('appearanceDetail')} onClick={onAppearance} /><SettingsRow icon={<Globe2 size={19} />} label={t('language')} detail={languages.find((option) => option.id === language)?.label} onClick={onLanguage} /></SettingsSection><SettingsSection title={t('game')}><SettingsRow icon={<CircleHelp size={19} />} label={t('rules')} onClick={onRules} /></SettingsSection><SettingsSection title={t('data')}><SettingsRow icon={<Archive size={19} />} label={t('history')} onClick={onHistory} /><SettingsRow icon={<Trash2 size={19} />} label={t('clearHistory')} danger onClick={onClearHistory} /><button className="settings-reset" type="button" onClick={onReset}><RotateCcw size={18} />{t('resetAppearance')}</button></SettingsSection><SettingsSection title={t('application')}><div className="settings-version"><span>{t('appVersion')}</span><strong>1.0.0</strong></div></SettingsSection></div> }
function SettingsSection({ title, children }: { title: string; children: ReactNode }) { return <section className="settings-section"><h3>{title}</h3><div className="settings-card">{children}</div></section> }
function SettingsRow({ icon, label, detail, danger, onClick }: { icon: ReactNode; label: string; detail?: string; danger?: boolean; onClick: () => void }) { return <button type="button" className={`settings-row ${danger ? 'danger' : ''}`} onClick={onClick}><span className="settings-row-icon">{icon}</span><span className="settings-row-copy"><strong>{label}</strong>{detail && <small>{detail}</small>}</span><ChevronRight size={18} /></button> }
function ClearHistory({ onCancel, onConfirm }: { onCancel: () => void; onConfirm: () => void }) { const { t } = useTranslation(); return <div className="confirm-content"><p>{t('clearHistoryQuestion')}</p><p className="sheet-intro">{t('clearHistoryDetail')}</p><div className="dialog-actions"><button className="dialog-cancel" type="button" onClick={onCancel}>{t('cancel')}</button><button className="dialog-danger" type="button" onClick={onConfirm}>{t('clear')}</button></div></div> }
function RulesView() { const { language, t } = useTranslation(); return <div className="rules-view"><p className="sheet-intro">{t('rulesIntro')}</p><RuleSection title={t('sectionOne')} categories={upperCategories.map((category) => ({ id: category.id, ...categoryText(language, category.id) }))} /><section className="rules-section"><h3>{t('bonusSection')}</h3><article className="rule-card"><strong>{t('bonusRuleTitle')}</strong><p>{t('bonusRule')}</p></article></section><RuleSection title={t('combinations')} categories={mainCategories.map((category) => ({ id: category.id, ...categoryText(language, category.id) }))} /><RuleSection title={t('chances')} categories={chanceCategories.map((category) => ({ id: category.id, ...categoryText(language, category.id) }))} /><section className="rules-section"><h3>{t('additionalRules')}</h3><article className="rule-card"><strong>{t('scratchTitle')}</strong><p>{t('scratchRule')}</p></article><article className="rule-card"><strong>{t('emptyTitle')}</strong><p>{t('emptyRule')}</p></article></section></div> }
function RuleSection({ title, categories }: { title: string; categories: readonly { id: string; label: string; description: string; scoreSummary: string }[] }) { return <section className="rules-section"><h3>{title}</h3><div className="rules-cards">{categories.map((category) => <article className="rule-card" key={category.id}><strong>{category.label}</strong><p>{category.description}</p><small>{category.scoreSummary}</small></article>)}</div></section> }
